### ISSUE TITLE
Not interpreting Pipes in Stylemodifiers for multiple Classes

### ISSUE THREAD

**Issue by fabianwitte** [geoffp/patternengine-node-handlebars#2]
I am using Pattern Lab Node `v2.5.1` on `Windows`, using the `grunt` configuration.

Using the following:
`{{> atoms-trigger-button:SP-Trigger--search|SP-Header__trigger("icon": "search") }}`
should result in having two classes add via `{{ styleModifier}}`.

Actually building fails with the following message:

`
Warning: Parse error on line 9:
...n:SP-Trigger--search|SP-Header__trigger(

-----------------------^

Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'OPEN_BLOCK_PARAMS', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', 'SEP', got 'CLOSE_BLOCK_PARAMS' Use --force to continue.
`

**Comment by geoffp** [comment]
Hi there! Style Modifiers and Pattern Parameters are not supported in the Node/Handlebars engine, because the functionality they provide is so easily done by natively passing parameters to Handlebars partials: http://handlebarsjs.com/partials.html.
